name = "reyhane"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "reyhane-registrations"
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "reyhane-receipts"

[vars]
MAX_CAPACITY = "20"
COURSE_PRICE = "2500000"
CARD_NUMBER = "6104337364737526"
CARD_HOLDER = "ریحانه زراعتکار"
